import React, { useState } from 'react';
import { useNavigate } from "react-router-dom";
import preview from '../assets/preview.png';
import Loader from '../components/loader';
import Form from '../components/form';
import { getRandomPrompt } from "../utils/index";

const CreateImage = () => {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    name: "",
    prompt: '',
    photo: ""
  });
  const [loading, setLoading] = useState(false);
  const [generatingImg, setGeneratingImg] = useState(false);

  // Handle input changes
  const handleChange = (e) => {
  
  };

  // Handle Surprise Me button
  const handleSurpriseMe = () => {
 
  };

  // Image Generation (Dummy function)
  const generateImg = () => {
  
  };

  // Handle Form Submission
  const handleSubmit = (e) => {

  };

  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>Create</h1>
        <br />
        <p className='text-gray-600'>
          Browse through a collection of imaginative and visually stunning images
          generated by DALL-E AI.
        </p>
      </div>

      <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-3'>
          <Form
            labelname="Your Name"
            type="text"
            name="name"
            placeholder="John Doe"
            value={form.name}
            handlechange={handleChange}
          />
          <Form
            labelname="Prompt"
            type="text"
            name="prompt"
            placeholder="A ghost shocked that humans can see it"
            value={form.prompt}
            handlechange={handleChange}
            issurpriseme={true}
            handlesurpriseme={handleSurpriseMe}
          />

          {/* Image Preview */}
          <div className='relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg 
          focus:ring-blue-500 focus:border-blue-600 w-64 h-64 p-3 flex justify-center items-center'>
            {form.photo ? (
              <img src={form.photo} alt={form.prompt} className='w-full h-full object-contain' />
            ) : (
              <img src={preview} alt="preview" className='w-1/2 h-1/2 opacity-40 object-contain' />
            )}

            {/* Loader Overlay */}
            {generatingImg && (
              <div className='absolute inset-0 z-0 flex justify-center items-center bg-[rgba(0,0,0,0.7)] rounded-lg'>
                <Loader />
              </div>
            )}
          </div>
        </div>

        {/* Generate & Submit Buttons */}
        <div className='flex mt-5 gap-5'>
          <button
            type='button'
            onClick={generateImg}
            className='bg-blue-600 text-white px-5 py-2 rounded-lg font-medium hover:bg-blue-700 transition-all'
          >
            {generatingImg ? "Generating..." : "Generate"}
          </button>

        
        </div>
      </form>
    </section>
  );
};

export default CreateImage;
