import React from 'react'
import { useState } from 'react'
import {useNavigate} from "react-router-dom"
import {preview} from "../assets/index"
import Loader from '../components/loader'
import Form from '../components/form'
import {getRandomPrompt}from "../utils/index"
const createimage = () => {
  const navigate=useNavigate()
  const [form,setform]=useState({
    name:"",
    prompt:'',
    photo:""
  })
  const [loading,setloading]=useState(false)
  const [generatingimg,setgeneratingimg]=useState(false)
const handlesubmit=(()=>{

})
  return (
   <section className='max-w-7xl mx-auto'>
 <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
Create
        </h1>
        <br />
        <p className='text-gray-600'>
          Browse through a collection of imaginative and visually stunning images
          generated by DALL-E AI.
        </p>
      </div>
      <form action="
      " className='mt-16 max-w-3xl' onSubmit={handlesubmit}>
        <div className='flex flex-col gap-3'>
          

        </div>
        
      </form>

   </section>
  )
}

export default createimage
