import React, { useState, useEffect } from 'react';
import Loader from '../components/loader';
import Card from '../components/carx';
import Form from '../components/form';

// Component to Render Cards
const Rendercards = ({ data, title }) => {
  if (data.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  } else {
    return (
      <h2 className='font-bold text-[#6469ff] text-xl uppercase'>
        {title}
      </h2>
    );
  }
};

const Home = () => {
  const [searchtext, setsearchtext] = useState('1222');
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState([]);

  return (
    <div className='w-max-7xl mx-auto'>
      {/* Header Section */}
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
          The Community Showcase
        </h1>
        <br />
        <p className='text-gray-600'>
          Browse through a collection of imaginative and visually stunning images
          generated by DALL-E AI.
        </p>
      </div>

      {/* Search Form */}
      <div className='mt-10'>
        <Form />
      </div>

      {/* Loader or Content */}
      <div className='mt-10'>
        {loading ? (
          <div className='flex justify-center items-center'>
            <Loader />
          </div>
        ) : (
          <>
            {/* Search Results Header */}
            {searchtext && (
              <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                Showing results for
                <span className='text-[#222328]'>{searchtext}</span>
              </h2>
            )}

            {/* Posts Grid */}
            <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
              {searchtext ? (
                <Rendercards data={[]} title='No posts found' />
              ) : (
                <Rendercards data={[]} title='No posts available' />
              )}
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default Home;
